config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
  resources :posts, only: [:index, :show, :new, :create] do
  resources :comments, only: [:new, :create]
  resources :likes, only: [:create]
  end
end
  # Defines the root path route ("/")
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_comment_count

  def update_comment_count
    post.increment!(:comment_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_like_count
  def update_like_count
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes
  has_many :comments

  def update_posts_count
    author.increment!(:post_counter)
  end

  def recent_five_comments
    comments.last(5)
  end

  validates :title, presence: true, length: { maximum: 250 }
  validates :comment_counter,
            numericality: { only_integer: true, greater_than_or_equal_to: 0,
                            message: 'must be an integer greater than or equal to zero.' }
  validates :likes_counter,
            numericality: { only_integer: true, greater_than_or_equal_to: 0,
                            message: 'must be an integer greater than or equal to zero.' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :posts, foreign_key: 'author_id'

  def three_recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  #   validates :name, presence: true
  #   validates :post_counter,
  #   numericality: { only_integer: true, greater_than_or_equal_to: 0,
  #                             message: 'must be an integer greater than or equal to zero' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # helper_method :current_user
  # def current_user
  #   @current_user ||= User.first
  # end
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @post = Post.find(params[:post_id])
    @comment.post = @post
    @comment.author = current_user
    if @comment.save
      redirect_to "/users/#{current_user.id}/posts", notice: 'comment created'
    else
      render 'posts/show'
    end
  end
end

  private

def comment_params
  params.require(:comment).permit(:text)
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @user = current_user
    @like = Like.new(author_id: @user.id, post_id: @post.id)
    return unless @like.save

    redirect_to user_posts_path(@user.id, @post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:author).where(author_id: params[:user_id])
    @user = User.includes(:posts, :comments).find(params[:user_id])
  end

  def show
    @post = User.find(params[:user_id]).posts.find(params[:id])
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @user = current_user
    @post = Post.new(author_id: @user, title: params[:post][:title], text: params[:post][:text])
    @post.author_id = @user.id
    @post.save
    redirect_to user_posts_path(@user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<div>
    <h3> Add new comment</h3>    
</div>

app/views/comments/new.html.erb
<%= form_with(model: @comment, url: user_post_comments_path, method: :post, scope: :comment) do |form| %>
        <div class="comment-form">
        <%= form.text_field :text, required: true, autofocus: true, placeholder: 'Add your comment here'%>
        <%= form.submit "Comment", class: "comment-button"%>
        <div>
    <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/likes/index.html.erb
<h1>Likes#index</h1>
<p>Find me in app/views/likes/index.html.erb</p>

app/views/posts/index.html.erb
<div class="detailed-post">

<div class="detail-container">
        <img src=<%=@user.photo %>>
        <div class="detail-user">
            <h1><%= @user.name %></h1>
            <h3>Number of posts: <%= @posts.count %>
            </h3>
        </div>
</div>


    <div class="recent-posts">
        <% @posts.includes({comments: [:author]}, :likes).each do |post| %>
        <div class="one-comment">
        <%= link_to user_post_path(@user, post.id) do%>
        <a href="/users/<%= @user.id %>/posts/<%= post.id %>" class=""><h1><%= post.title %></h1></a>
                <p id="post-text">
                    <%= post.text.split[0..80].join(" ") %>
                </p>
                <div class="comment-like">
                    <span>Comments: <%= post.comment_counter%> </span>
                    <span class="likes">Likes:<%= post.likes_counter%></span>
                </div>
              
                <div class="comments-container">
                    <% post.recent_five_comments.each do |comment| %>
                        <div  id="single-comment"> 
                           <span> <%= comment.author.name %> : <%= comment.text %></span>
                        </div>
                    <% end %>
            </div>
            <%end%>
            </div>
        <% end %>
    </div>
    </div>

app/views/posts/new.html.erb
<h2>Add new post</h2>
<%= form_with model: @post, url: user_posts_path(@user) do |form| %>
      <div class="form-container">
        <%= form.text_field :title, required: true, autofocus: true, class: "form-input" %>
        <%= form.text_area :text, required: true, autofocus: true, class: "form-input" %>
        <%= form.submit "Create", class: "create-button" %>
      </div>
    <% end %>

app/views/posts/show.html.erb
  <div class="comment-container">
    <div class='comment-header'>
    
        <h1 id="post-title">
           "<%= @post.title%>" - <%= @post.author.name%>
        </h1>
        <div class="comment-like">
            <span>Comments: <%= @post.comment_counter%>, </span>
            <span class="likes">Likes:<%= @post.likes_counter%></span>
        </div>
    </div>
    <p>
        <%= @post.text%>
    </p>
    <div class="comment-like-button">
        <%= form_with url: "/users/#{@post.author.id}/posts/#{@post.id}/likes" do |form| %>
     <%= form.submit 'Like', class: 'single-button' %>
  <% end %>
  <div><%= link_to "Add Comment", new_user_post_comment_path(@post.author.id, @post.id) %></div>
    </div>
    
            <div class="comments-container-post">
                <% @comments=Post.find(@post.id).comments %>
                    <% @comments.includes(:author).each do |comment| %>
                        <div  id="single-comment">
                            <span> <%= comment.author.name %> : <%= comment.text %></span>
                        </div>
                    <% end %>
    </div>
</div>

app/views/users/_user.html.erb
<a href="/users/<%= user.id %>">
  <div class="users-list">
    <img src="<%= user.photo %>" alt="User" />
    <div class="description">
      <h2><%=user.name %></h2>
      <h4>Number of posts: <%= user.posts.count %></h4>
    </div>
  </div>
</a>

app/views/users/index.html.erb
<div><%= button_to "Sign out", destroy_user_session_path, class: "sign_out", method: :delete %><div>
<div class="container">
  <h1 class="heading">RailsBlog</h1>
  <% @users.each do |user| %>
    <%= render partial: "users/user", locals: { user: user } %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user-detail">
    <div class="detail-description">
    <div><img src="<%= @user.photo %>" alt="User" /></div>
    <div class="user-desc">
        <h1> <%= @user.name %></h1>
        <h3>Number of posts: <%= @user.posts.count %></h3>
    </div>
    </div>
    <div class="bio">
        <h2>Bio</h2>
        <p><%= @user.bio %></p>
    </div>
    <% @user.three_recent_posts.each do |post| %>
    <div class="recent-posts">
        <div class="single-post">
        
            <h2><a href="/users/<%= @user.id %>/posts/<%= post.id %>" class=""><%= post.title %></a></h2>
            <p><%= post.text %></p>
             <div class="comment-like">
                    <span class="comments">Comments: <%= post.comment_counter%>, </span>
                    <span class="likes">Likes:<%= post.likes_counter%></span>
                </div>
        
        </div>
         <a href="<%=@user.id%>/posts/" class="button">See all posts</a>
    </div>
    <%end%> 

</div>